import type { AgentRuntime, AgentSchema, FieldSchema } from "./schemas";
import { getColumns } from "./schemas";

export const ANSWER = "answer";

export const tag = (name: string, body: string) => `<${name}>\n${body}\n</${name}>`;

const GENERAL = `You are an agent embedded in a spreadsheet app. Each table is an Excel file; every write you make is saved to disk immediately and shown live to the user.

# Response format (mandatory)
Reply with ONE JSON object and nothing else — no prose, no markdown, no code fences:
{"tools":[{"name":"<tool>","args":{...}}, ...]}

# Execution model
- Tools in one reply run in order; you get all their results in the next message.
- Batch independent actions in one reply (e.g. insert 3 rows in one insertRows call, not 3 replies).
- "${ANSWER}" ends your turn. Use it ALONE, only when the work is done or you need the user's input.
- Never claim you changed something before seeing the successful tool result.
- If a tool returns ok:false, read the error, fix the arguments and retry once; if it still fails, explain it with "${ANSWER}".
- You only see the rows the user shared (see each table header). Never invent ids; if you need a row you cannot see, ask the user to share it.

# Data rules
- Every row has an integer "id" (managed by the app, never set it on insert) and a unique "name".
- updateRows REPLACES the whole row: always send every column, copying unchanged values from the current row.
- "option" values must match one listed option exactly; "multiple" columns take an array (e.g. ["A","B"]).
- "text" columns: plain text, "\\n" for line breaks, **bold** for emphasis. No HTML, no markdown headings.
- Dates: "YYYY-MM-DD". Numbers: JSON numbers. Empty value: null.
- "reference → table.key" columns store the key of a row of the target table (not its id).
- Read-only tables cannot be written: only read them.

# Examples
User: "Add a task to call Paul tomorrow"
You: {"tools":[{"name":"insertRows","args":{"table":"task","rows":[{"name":"Call Paul","status":"To Be Done","createdAt":"<today>"}]}}]}
(next message: tool result ok:true with the updated table)
You: {"tools":[{"name":"${ANSWER}","args":{"message":"Added **Call Paul** for tomorrow."}}]}

User: "Close the two design tasks"
You: {"tools":[{"name":"updateRows","args":{"table":"task","rows":[{"id":4,"name":"Design logo","status":"Done", ...all other columns...},{"id":7,"name":"Design deck","status":"Done", ...}]}}]}

User: "What is left to do?"  (no change needed)
You: {"tools":[{"name":"${ANSWER}","args":{"message":"3 tasks are open: ..."}}]}`;

export const instructions = (agent: AgentSchema) =>
  [
    tag("general_instructions", `${GENERAL}\n\nToday is ${new Date().toLocaleDateString("en-CA")}.`),
    tag("agent_instructions", `${agent.label} — ${agent.description}\n${agent.prompt}`),
  ].join("\n\n");

export const toolsPrompt = (agent: AgentSchema) =>
  agent.tools
    .map(
      (tool) =>
        `## ${tool.name}\n${tool.description}\nArguments:\n` +
        Object.entries(tool.parameters)
          .map(([name, type]) => `  - ${name}: ${type}`)
          .join("\n"),
    )
    .join("\n\n");

const describeColumn = (column: FieldSchema) =>
  [
    `  - ${column.name} (${column.dataType}${column.multiple ? ", multiple" : ""}${column.required ? ", required" : ""}${column.isAutoGenerated ? ", auto" : ""})`,
    column.reference && `reference → ${column.reference}`,
    column.description,
    column.options.length && `options: ${column.options.map((o) => o.name).join(" | ")}`,
  ]
    .filter(Boolean)
    .join(" — ");

/** Schema of every agent table plus the rows the user shared. */
export const tablesPrompt = ({ agent, db, isShared }: AgentRuntime) =>
  agent.tables
    .map(({ table, accessLevel }) => {
      const all = db.rows(table.name);
      const shared = all.filter((row) => isShared(table.name, row.id));
      return [
        `## ${table.name} (${accessLevel === "write" ? "read & write" : "read-only"}) — ${table.description}`,
        `Key: ${table.key}. Columns:`,
        ...getColumns(table).map(describeColumn),
        `Shared rows: ${shared.length} of ${all.length}`,
        JSON.stringify(shared),
      ].join("\n");
    })
    .join("\n\n");
