import type { ComponentType } from "react";
import { z } from "zod";
import type { Database } from "./crud-table";

export const MODELS = ["gpt-5", "gpt-6-luna"] as const;

export const conversationSchema = z.object({
  id: z.string(),
  title: z.string(),
  agent: z.string(),
  tables: z
    .array(z.object({ table: z.string(), path: z.string() }))
    .default([]),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});

export type ConversationSchema = z.infer<typeof conversationSchema>;

export const messageSchema = z.object({
  id: z.string(),
  content: z.string(),
  role: z.enum(["user", "assistant", "system"]),
  model: z.string().optional(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
  conversationId: z.string(),
});

export type MessageSchema = z.infer<typeof messageSchema>;

// Migrates the former `openaiKey` field.
const renameOpenaiKey = (value: unknown) =>
  value && typeof value === "object" && "openaiKey" in value && !("aiKey" in value)
    ? { ...value, aiKey: (value).openaiKey }
    : value;

export const settingsSchema = z.preprocess(renameOpenaiKey, z.object({
  aiKey: z.string().default(""),
  model: z.enum(MODELS).default("gpt-5"),
  agent: z.string().default(""),
  // Active conversation id per agent name.
  conversations: z.record(z.string(), z.string()).default({}),
  // Absolute path of the workspace folder, used to store full image paths in Excel.
  workspacePath: z.string().default(""),
  // Power BI access token (from `bun run pbi-token`) and when it was saved (ms).
  pbiToken: z.string().default(""),
  pbiTokenAt: z.number().default(0),
  // Per-agent state set by custom tabs (active dataset, report, page…).
  agentState: z.record(z.string(), z.record(z.string(), z.string())).default({}),
}));

export type SettingsSchema = z.infer<typeof settingsSchema>;

export const OPTION_COLORS = [
  "cyan",
  "green",
  "yellow",
  "red",
  "purple",
  "blue",
  "gray",
  "orange",
  "pink",
  "brown",
  "black",
  "white",
  "lime",
  "teal",
  "indigo",
  "violet",
] as const;

export type OptionColor = (typeof OPTION_COLORS)[number];

export const fieldSchema = z.object({
  name: z.string(),
  description: z.string().optional().default(""),
  dataType: z
    .enum([
      "string",
      "text",
      "number",
      "boolean",
      "option",
      "date",
      "url",
      "image",
      "file",
      "json",
    ])
    .optional()
    .default("string"),
  options: z
    .array(
      z.object({
        name: z.string(),
        description: z.string().optional(),
        color: z.enum(OPTION_COLORS).optional().default("gray"),
      }),
    )
    .optional()
    .default([]),
  required: z.boolean().optional().default(false),
  default: z.any().optional(),
  isAutoGenerated: z.boolean().optional(),
  multiple: z.boolean().optional().default(false),
  /** Soft foreign key: target table name; the cell stores the target row key. */
  reference: z.string().optional(),
});

export type FieldSchema = z.infer<typeof fieldSchema>;
export type FieldOption = FieldSchema["options"][number];

export const tableSchema = z.object({
  name: z.string(),
  description: z.string().optional().default(""),
  /** Column other tables reference this table by (Power BI id, or name). */
  key: z.string().optional().default("name"),
  columns: z.array(fieldSchema),
  config: z.array(fieldSchema).optional().default([]),
});

export type TableSchema = z.infer<typeof tableSchema>;

export type CellValue = string | number | boolean | string[] | null;
export type Row = { id: number; name: string; [column: string]: CellValue };

const idColumn = fieldSchema.parse({
  name: "id",
  description: "Unique auto-incremented integer",
  dataType: "number",
  isAutoGenerated: true,
});

/** Table columns with the implicit `id` column first. */
export const getColumns = (table: TableSchema): FieldSchema[] => [
  idColumn,
  ...table.columns.filter((column) => column.name !== "id"),
];

/** Everything an agent run (tools, context hooks) can access. */
export type AgentRuntime = {
  db: Database;
  agent: AgentSchema;
  conversationId: string;
  /** State set by the agent's custom tabs (active dataset, report, page…). */
  state: Record<string, string>;
  /** Rows the user selected to share with the agent. */
  isShared: (table: string, id: number) => boolean;
};

export type ToolContext = AgentRuntime;

export type ToolSchema = {
  name: string;
  description: string;
  /** Parameter name → type and description, shown to the model. */
  parameters: Record<string, string>;
  execute: (args: any, context: ToolContext) => unknown;
};

export type CustomTabProps = { agent: AgentSchema; db: Database };

export type AgentSchema = {
  name: string;
  label: string;
  description: string;
  prompt: string;
  tables: { table: TableSchema; accessLevel: "read" | "write" }[];
  tools: ToolSchema[];
  /** Extra tabs rendered next to the table tabs. */
  tabs?: {
    name: string;
    label: string;
    component: ComponentType<CustomTabProps>;
  }[];
  /** Extra context added to each user message (can also prepare rows). */
  context?: (runtime: AgentRuntime) => string | Promise<string>;
  /** Called by write tools after rows changed (e.g. to refresh computed columns). */
  afterWrite?: (table: string, rows: Row[], runtime: AgentRuntime) => Promise<void>;
};
