import type { ToolSchema } from "@/lib/schemas";
import { afterWrite, writableTable } from "./table-access";

export const insertRowsTool: ToolSchema = {
  name: "insertRows",
  description: `Create one or more rows in a writable table. Ids are generated by the app: never send "id".
Each row must contain a unique "name" and every required column; omitted columns are left empty.
Returns the table's shared rows after the insert (new rows included, with their ids).
Example: {"name":"insertRows","args":{"table":"task","rows":[{"name":"Write brief","status":"To Be Done"},{"name":"Review brief","status":"To Be Done"}]}}`,
  parameters: {
    table: "string — table name",
    rows: "object[] — rows without id",
  },
  execute: async (args: { table: string; rows: Record<string, unknown>[] }, ctx) => {
    const table = writableTable(ctx, args.table);
    const created = await ctx.db.insert(table.name, args.rows);
    return afterWrite(ctx, table.name, created);
  },
};
