import { tableSchema } from "@/lib/schemas";

export const pbiReportTable = tableSchema.decode({
  name: "pbiReport",
  description: "A table for Power BI reports",
  columns: [
    {
      name: "powerBiReportId",
      description: "The ID of the report",
      dataType: "string",
      required: true,
    },
    {
      name: "powerBiDatasetId",
      description: "The ID of the dataset of the report",
      dataType: "string",
      required: true,
    },
    {
      name: "name",
      description: "The name of the report",
      dataType: "string",
      required: true,
    },
    {
      name: "result",
      description: "The result of the DAX query",
      dataType: "string",
      required: false,
      isAutoGenerated: true,
    },
  ],
  config: [],
});
