import { tableSchema } from "@/lib/schemas";

export const VISUAL_TYPES = [
  "card", "multiRowCard", "kpi", "gauge", "tableEx", "pivotTable",
  "clusteredColumnChart", "stackedColumnChart", "clusteredBarChart", "stackedBarChart",
  "lineChart", "areaChart", "lineClusteredColumnComboChart", "pieChart", "donutChart",
  "scatterChart", "waterfallChart", "funnel", "treemap", "map", "filledMap",
  "slicer", "textbox", "image", "shape", "actionButton", "other",
] as const;

export const reportVisualTable = tableSchema.decode({
  name: "reportVisual",
  description: "Visuals of the report pages: type, position, fields by role, filters, formatting and computed data",
  key: "powerBiVisualId",
  columns: [
    { name: "powerBiVisualId", description: "Visual id (Power BI visual name, or a readable unique id like \"v-sales-by-region\")", dataType: "string", required: true },
    { name: "name", description: "Unique label: \"<page> · <title>\"", dataType: "string", required: true },
    { name: "powerBiPageId", description: "Page of the visual", dataType: "string", reference: "reportPage", required: true },
    { name: "powerBiReportId", description: "Report of the visual", dataType: "string", reference: "pbiReport" },
    { name: "title", dataType: "string" },
    { name: "type", description: "Power BI visual type", dataType: "option", options: VISUAL_TYPES.map((name) => ({ name, color: "gray" as const })) },
    { name: "x", description: "Left position in px on the page canvas", dataType: "number" },
    { name: "y", description: "Top position in px", dataType: "number" },
    { name: "width", dataType: "number" },
    { name: "height", dataType: "number" },
    { name: "z", description: "Stacking order", dataType: "number" },
    { name: "hidden", dataType: "boolean" },
    { name: "category", description: "Axis / rows / slicer fields: Table[Column]", dataType: "string", multiple: true },
    { name: "series", description: "Legend / matrix columns: Table[Column]", dataType: "string", multiple: true },
    { name: "values", description: "Values: [Measure] or Table[Column] (summed)", dataType: "string", multiple: true },
    { name: "fields", description: "All fields by Power BI data role (JSON, imported)", dataType: "json", isAutoGenerated: true },
    { name: "filters", description: "JSON array: [{\"field\":\"Table[Column]\",\"operator\":\"In\"|\"NotIn\",\"values\":[…]}]", dataType: "json" },
    { name: "format", description: "JSON formatting: {\"color\":\"#hex\",\"colors\":[…],\"background\":\"#hex\",\"titleColor\":\"#hex\",\"fontSize\":12,\"showLegend\":true,\"showDataLabels\":false}", dataType: "json" },
    { name: "dax", description: "DAX generated by the app from the fields (read-only)", dataType: "text", isAutoGenerated: true },
    { name: "data", description: "Result of the visual query (first rows, read-only)", dataType: "text", isAutoGenerated: true },
    { name: "description", dataType: "text" },
  ],
});
