import { tableSchema } from "@/lib/schemas";

export const reportVisualTable = tableSchema.decode({
  name: "reportVisual",
  description: "A table for report visuals",
  columns: [
    {
      name: "powerBiPageId",
      description: "The ID of the page",
      dataType: "string",
      isAutoGenerated: true,
    },
    {
      name: "powerBiReportId",
      description: "The ID of the report",
      dataType: "string",
      isAutoGenerated: true,
    },
    {
      name: "powerBiVisualId",
      description: "The ID of the visual",
      dataType: "string",
      isAutoGenerated: true,
    },
    {
      name: "name",
      description: "The name of the visual",
      dataType: "string",
      required: true,
    },
    {
      name: "description",
      description: "The description of the visual",
      dataType: "text",
    },
    {
      name: "type",
      dataType: "option",
      options: [
        {
          name: "Table",
        },
        {
          name: "Chart",
        },
      ],
    },
    {
      name: "values",
      dataType: "string",
      multiple: true,
    },
    {
      name: "columns",
      dataType: "string",
      multiple: true,
    },
    {
      name: "rows",
      dataType: "string",
      multiple: true,
    },
    {
      name: "filters",
      dataType: "string",
      multiple: true,
    },
  ],
  config: [],
});
