import { tableSchema } from "@/lib/schemas";

export const reportTable = tableSchema.decode({
  name: "pbiReport",
  description: "Power BI reports: imported from an embed link, or designed in the builder",
  key: "powerBiReportId",
  columns: [
    { name: "powerBiReportId", description: "Report id (Power BI id, or a readable unique id for built reports)", dataType: "string", required: true },
    { name: "name", description: "Report name", dataType: "string", required: true },
    { name: "powerBiDatasetId", description: "Dataset the report reads", dataType: "string", reference: "dataset" },
    { name: "powerBiGroupId", description: "Workspace id", dataType: "string", isAutoGenerated: true },
    {
      name: "source",
      dataType: "option",
      options: [
        { name: "Imported", color: "blue" },
        { name: "Built", color: "green" },
      ],
    },
    { name: "embedUrl", dataType: "url", isAutoGenerated: true },
    { name: "filters", description: "Report-level filters (JSON, see reportVisual.filters)", dataType: "json" },
    { name: "description", dataType: "text" },
  ],
});
