/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportDatasetRouteImport } from './routes/import-dataset'
import { Route as ImportReportRouteImport } from './routes/import-report'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportDatasetRoute = ImportDatasetRouteImport.update({
  id: '/import-dataset',
  path: '/import-dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportReportRoute = ImportReportRouteImport.update({
  id: '/import-report',
  path: '/import-report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import-dataset': typeof ImportDatasetRoute
  '/import-report': typeof ImportReportRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import-dataset': typeof ImportDatasetRoute
  '/import-report': typeof ImportReportRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import-dataset': typeof ImportDatasetRoute
  '/import-report': typeof ImportReportRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/import-dataset' | '/import-report' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/import-dataset' | '/import-report' | '/settings'
  id: '__root__' | '/' | '/import-dataset' | '/import-report' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportDatasetRoute: typeof ImportDatasetRoute
  ImportReportRoute: typeof ImportReportRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-dataset': {
      id: '/import-dataset'
      path: '/import-dataset'
      fullPath: '/import-dataset'
      preLoaderRoute: typeof ImportDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-report': {
      id: '/import-report'
      path: '/import-report'
      fullPath: '/import-report'
      preLoaderRoute: typeof ImportReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportDatasetRoute: ImportDatasetRoute,
  ImportReportRoute: ImportReportRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
